name: Docker build and push
 
on:
  push:
    branches:
    - main 
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * 4'

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
    - name: "Build"
      env:
        DOCKER_BUILDKIT: 1
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
      run: |
        sudo apt-get update -qq && \
        sudo apt-get install --no-install-recommends -qqy \
          jq && \
        VERSION="$(curl -sSL https://api.github.com/repos/microsoft/vscode/releases/latest | jq -r .tag_name)" && \
        docker build --cache-from=poad/docker-vscode:latest --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg VSCODE_VERSION="${VERSION}" -t poad/docker-vscode:latest  .
    - name: Hadolint
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
      uses: brpaz/hadolint-action@master
  
  docker_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      if: github.event_name != 'pull_request' && github.event_name != 'schedule' && env.CHANGE_STATE != 'changed'
    - name: Build
      env:
        DOCKER_BUILDKIT: 1
      if: github.event_name != 'pull_request' && github.event_name != 'schedule' && env.CHANGE_STATE != 'changed'
      run: |
        sudo apt-get update -qq && \
        sudo apt-get install --no-install-recommends -qqy \
          jq && \
        VSCODE_VERSION_BASE="$(curl -sSL https://api.github.com/repos/microsoft/vscode/releases/latest | jq -r .tag_name)" && \
        CODE_SERVER_VERSION="$(curl -sSL https://api.github.com/repos/cdr/code-server/releases/latest | jq -r .tag_name)" && \
        docker build --cache-from=poad/docker-vscode:latest --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg VSCODE_VERSION="${VSCODE_VERSION}" --build-arg VSCODE_VERSION_BASE="$(echo "${VSCODE_VERSION}" | cut -d'.' -f 1-2)" --build-arg CODE_SERVER_VERSION="${CODE_SERVER_VERSION}" --build-arg CODE_SERVER_BRANCH=jsjoeio/upgrade-vscode-1.54 -t poad/docker-vscode:${CODE_SERVER_VERSION}-${VSCODE_VERSION} . && \
        echo "VSCODE_VERSION=${VSCODE_VERSION}" >> $GITHUB_ENV
        echo "CODE_SERVER_VERSION=${CODE_SERVER_VERSION}" >> $GITHUB_ENV
    - name: Push
      env:
        VSCODE_VERSION: ${{ env.VSCODE_VERSION }}
        CODE_SERVER_VERSION: ${{ env.CODE_SERVER_VERSION }}
      if: github.event_name != 'pull_request' && github.event_name != 'schedule' && env.CHANGE_STATE != 'changed'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u poad --password-stdin && \
        docker push poad/docker-vscode:${CODE_SERVER_VERSION}-${VSCODE_VERSION} && \
        docker tag poad/docker-vscode:${CODE_SERVER_VERSION}-${VSCODE_VERSION} poad/docker-vscode:latest
        docker push poad/docker-vscode:latest

